### ISSUE TITLE
Getting cuda memory error

### ISSUE THREAD

**Issue by faysalhossain2007** [microsoft/CodeBERT#126]
Even though there is no process running on GPU, code seems to face memory issue: 

```
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: CUDA out of memory. Tried to allocate 150.00 MiB (GPU 0; 7.93 GiB total capacity; 6.66 GiB already allocated; 92.69 MiB free; 6.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

It occurs in 

```
  File "run.py", line 629, in <module>
    main()
  File "run.py", line 450, in main
    loss,_,_ = model(source_ids,source_mask,position_idx,att_mask,target_ids,target_mask)

```

I also reduces the batch size from 32 to 15. But it didn't help.
I am using the following command to run the code:

```
source=java
target=cs
lr=1e-4
batch_size=15
beam_size=10
source_length=320
target_length=256
output_dir=saved_models/$source-$target/
train_file=data/train.java-cs.txt.$source,data/train.java-cs.txt.$target
dev_file=data/valid.java-cs.txt.$source,data/valid.java-cs.txt.$target
epochs=3
pretrained_model=microsoft/graphcodebert-base

mkdir -p $output_dir
python run.py \
--do_train \
--do_eval \
--model_type roberta \
--source_lang $source \
--model_name_or_path $pretrained_model \
--tokenizer_name microsoft/graphcodebert-base \
--config_name microsoft/graphcodebert-base \
--train_filename $train_file \
--dev_filename $dev_file \
--output_dir $output_dir \
--max_source_length $source_length \
--max_target_length $target_length \
--beam_size $beam_size \
--train_batch_size $batch_size \
--eval_batch_size $batch_size \
--learning_rate $lr \
--num_train_epochs $epochs 2>&1| tee $output_dir/train.log
```

I even tried with batch size of 8.

**Comment by faysalhossain2007** [comment]
The following solution works for me-

```
source_length=160
target_length=128
```

Keeping my note here in case it helps other people.
